name: mazadat
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  rxdart: ^0.28.0
  flutter_bloc: ^7.0.0
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.0.11
  pin_code_text_field: ^1.8.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  app_settings: ^5.1.1
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  share_plus: ^10.0.3
  pin_code_fields: ^8.0.1
  modal_bottom_sheet: ^3.0.0
  expandable: ^5.0.1
  fluttertoast: ^8.2.5
  equatable: ^2.0.7
  iconsax: ^0.0.8
  flutter_animate: ^4.5.2
  glassmorphism_widgets: ^0.2.2
  just_audio: ^0.9.33
  audio_waveforms: ^1.2.0
  path_provider: ^2.1.1
  file_picker: ^8.1.6
  flutter_form_builder: ^10.0.1
  photo_view: ^0.15.0
  expandable_text: ^2.3.0
  dio_cache_interceptor: ^3.5.1
  google_fonts: ^6.2.1
  responsive_builder: ^0.7.1
  dartz: ^0.10.1
  flutter_widget_from_html: ^0.15.3
  flutter_staggered_grid_view: ^0.7.0
  collection: ^1.19.0
  internet_connection_checker: ^3.0.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.2
  loader_overlay: ^5.0.0
  hexcolor: ^3.0.1
  app_links: ^3.5.0
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  lottie: ^3.3.1
  go_router: ^15.1.1
  glass_kit: ^4.0.1
  dotted_border: ^3.0.1
  video_player: ^2.10.0
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  pusher_channels_flutter: ^2.5.0
  flutter_sliding_toast: ^1.5.2
  shared_preferences: ^2.5.3
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/images/
    - assets/langs/
    - assets/launchers/
    - assets/audio/
    - assets/lottie/
    - assets/gif/

  fonts:
    - family: en
      fonts:
        - asset: assets/fonts/en/thin.ttf
          weight: 200
        - asset: assets/fonts/en/light.ttf
          weight: 300
        - asset: assets/fonts/en/regular.ttf
          weight: 400
        - asset: assets/fonts/en/medium.ttf
          weight: 500
        - asset: assets/fonts/en/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/en/bold.ttf
          weight: 700
        - asset: assets/fonts/en/extra_bold.ttf
          weight: 800
        - asset: assets/fonts/en/black.ttf
          weight: 900

