name: mazadat
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  rxdart: ^0.28.0
  flutter_bloc: ^7.0.0
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.0.11
  pin_code_text_field: ^1.8.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  app_settings: ^5.1.1
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  share_plus: ^10.0.3
  pin_code_fields: ^8.0.1
  modal_bottom_sheet: ^3.0.0
  expandable: ^5.0.1
  fluttertoast: ^8.2.5
  equatable: ^2.0.7
  iconsax: ^0.0.8
  flutter_animate: ^4.5.2
  glassmorphism_widgets: ^0.2.2
  just_audio: ^0.9.33
  audio_waveforms: ^1.2.0
  path_provider: ^2.1.1
  file_picker: ^8.1.6
  flutter_form_builder: ^10.0.1
  photo_view: ^0.15.0
  expandable_text: ^2.3.0
  dio_cache_interceptor: ^3.5.1
  google_fonts: ^6.2.1
  responsive_builder: ^0.7.1
  dartz: ^0.10.1
  flutter_widget_from_html: ^0.15.3
  flutter_staggered_grid_view: ^0.7.0
  collection: ^1.19.0
  internet_connection_checker: ^3.0.1
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.14.2
  loader_overlay: ^5.0.0
  hexcolor: ^3.0.1
  app_links: ^3.5.0
  device_info_plus: ^11.3.0
  package_info_plus: ^8.3.0
  lottie: ^3.3.1
  go_router: ^15.1.1
  glass_kit: ^4.0.1
  dotted_border: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/lunchers/logo_710x599.png"
  image_path_ios: "assets/lunchers/logo_1024x1024.png"
  adaptive_icon_background: "assets/lunchers/icon_with_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/lunchers/logo_432x432.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/lunchers/logo_432x432.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  background_color_ios: "#ffffff"
  background_color_android: "#ffffff"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/lunchers/icon_with_background.png"
  windows:
    generate: true
    image_path: "assets/lunchers/icon_with_background.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/lunchers/icon_with_background.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/lunchers/logo_for_splash.png
  android_12:
    image: assets/lunchers/splash_android_12.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
  ios_content_mode: center
  android_gravity: center
  web_image_mode: center
  fullscreen: true
  android: true
  ios: true
  web: false


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/svgs/nav_bar/
    - assets/svgs/settings/
    - assets/svgs/merchant_card_icons/
    - assets/images/
    - assets/langs/
    - assets/lunchers/
    - assets/audio/
    - assets/lottie/
